import path from 'path';
import type { CompilerCtx, ComponentCompilerMeta, Config } from '@stencil/core/internal';
import type { OutputTargetAngular, PackageJSON } from './types';
import { relativeImport, normalizePath, sortBy, readPackageJson, dashToPascalCase, getCustomElementsDir, flattenImportCollection } from './utils';
import { createComponentDefinitions } from './component/generate-angular-components';
import generateValueAccessors from './generate-value-accessors';
import { ImportCollection } from './component/types';
import { setComponentNamespaceImport } from './component/utils/set-component-namespace-import';
import { generateAngularProxyEntryPoint } from './component/generate-angular-proxy-entry-point';

export async function angularComponentProxyOutput(
  compilerCtx: CompilerCtx,
  outputTarget: OutputTargetAngular,
  components: ComponentCompilerMeta[],
  config: Config,
) {
  const filteredComponents = getFilteredComponents(components, outputTarget.excludeComponents);
  const rootDir = config.rootDir as string;
  const pkgData = await readPackageJson(config, rootDir);

  const finalText = generateProxies(
    filteredComponents,
    pkgData,
    outputTarget,
    config.rootDir as string,
  );

  await Promise.all([
    compilerCtx.fs.writeFile(outputTarget.directivesProxyFile, finalText),
    copyResources(config, outputTarget),
    generateAngularProxyEntryPoint(compilerCtx, filteredComponents, outputTarget),
    generateValueAccessors(compilerCtx, filteredComponents, outputTarget, config),
  ]);
}

/**
 * Returns a filtered list of components excluding component tag selectors
 * that have been referenced in the `excludeComponents` array.
 *
 * @param components The list of all components from the Stencil compiler.
 * @param excludeComponents The list of component tag selectors to exclude.
 */
function getFilteredComponents(components: ComponentCompilerMeta[], excludeComponents: string[] = []) {
  return sortBy(components, (c) => c.tagName).filter(
    (c) => !excludeComponents.includes(c.tagName) && !c.internal,
  );
}

/**
 * Copies the contents of the `../angular-component-lib` directory to the
 * project's destination directory.
 *
 * Files are copied instead of referenced from a named package to avoid
 * having to add a `dependency` to the project's `package.json`.
 */
async function copyResources(config: Config, outputTarget: OutputTargetAngular) {
  if (!config.sys || !config.sys.copy || !config.sys.glob) {
    throw new Error('Stencil is not properly initialized at this step. Notify the developer');
  }
  const srcDirectory = path.join(__dirname, '..', 'angular-component-lib');
  const destDirectory = path.join(
    path.dirname(outputTarget.directivesProxyFile),
    'angular-component-lib',
  );

  return config.sys.copy(
    [
      {
        src: srcDirectory,
        dest: destDirectory,
        keepDirStructure: false,
        warn: false,
      },
    ],
    srcDirectory,
  );
}

export function generateProxies(
  components: ComponentCompilerMeta[],
  pkgData: PackageJSON,
  outputTarget: OutputTargetAngular,
  rootDir: string,
) {
  const distTypesDir = path.dirname(pkgData.types);
  const dtsFilePath = path.join(rootDir, distTypesDir, 'components.d.ts');
  const componentsTypeFile = relativeImport(outputTarget.directivesProxyFile, dtsFilePath, '.d.ts');

  const angularCoreImports = ['ChangeDetectionStrategy', 'ChangeDetectorRef', 'Component', 'ElementRef', 'EventEmitter', 'NgZone'];

  const imports: ImportCollection = {
    ['@angular/core']: angularCoreImports,
  };

  if (outputTarget.singleComponentAngularModules) {
    // If we are generating SCAM modules, we need to import the `NgModule` decorator.
    // The generated Angular modules will rely on `CommonModule`.
    imports['@angular/core'].push('NgModule');
    imports['@angular/common'] = ['CommonModule'];
  }

  setComponentNamespaceImport(outputTarget, componentsTypeFile, imports);

  if (outputTarget.includeImportCustomElements) {
    if (outputTarget.componentCorePackage !== undefined) {
      for (const { tagName } of components) {
        const defineCustomElementFn = `define${dashToPascalCase(tagName)}`;
        const filePath = `${normalizePath(outputTarget.componentCorePackage!)}/${getCustomElementsDir(outputTarget.customElementsDir)}/${tagName}.js`;
        imports[filePath] = [`defineCustomElement as ${defineCustomElementFn}`];
      }
    }
  }

  imports['./angular-component-lib/utils'] = ['ProxyCmp', 'proxyOutputs'];

  const componentClasses = components.map(createComponentDefinitions(
    outputTarget,
    imports
  ));

  const final: string[] = [
    `/*
 * This file is auto-generated by @stencil/angular-output-target.
 * Any changes you make to this file will be overwritten.
 */`,
    flattenImportCollection(imports),
    componentClasses.join('\n')
  ];

  return final.join('\n') + '\n';
}

