import type { ComponentCompilerMeta } from '@stencil/core/internal';
import { Project } from 'ts-morph';
import { kebabToPascalCase } from './utils/string-utils';

export const createStencilNextComponents = ({
  components,
  moduleSpecifier,
}: {
  components: ComponentCompilerMeta[];
  moduleSpecifier: string;
}) => {
  const project = new Project({ useInMemoryFileSystem: true });
  const useClientDirective = `'use client';\n\n`;
  const disableEslint = `/* eslint-disable */\n`;
  const autogeneratedComment = `/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */\n\n`;

  const sourceFile = project.createSourceFile(
    'component.ts',
    useClientDirective + autogeneratedComment + disableEslint
  );

  for (const component of components) {
    const tagName = component.tagName;
    const reactTagName = kebabToPascalCase(tagName);
    sourceFile.addExportDeclaration({
      moduleSpecifier,
      namedExports: [reactTagName],
    });
  }

  sourceFile.organizeImports();
  sourceFile.formatText();

  return sourceFile.getFullText();
};
