name: 🐛 Bug Report
description: Create a report to help us improve the Stencil Framework Output Targets
title: 'bug: '
body:
  - type: markdown
    attributes:
      value: |
        At this time, this repository is maintained on an as-needed basis for the Ionic Framework.
        As a result, we may not immediately get around to resolving your issue.
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I have searched for [existing issues](https://github.com/ionic-team/stencil-ds-output-targets/issues) that already report this problem, without success.
          required: true
  - type: input
    attributes:
      label: Stencil Version
      description: The version number of Stencil where the issue is occurring.
    validations:
      required: true
  - type: dropdown
    id: stencil-framework-output-target
    attributes:
      label: Stencil Framework Output Target
      description: Which Stencil Framework Output Target are you using?
      options:
        - Angular
        - React
        - Vue
    validations:
      required: true
  - type: input
    attributes:
      label: Stencil Framework Output Target Version
      description: Which version of Framework Output Target are you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests. For example, what does the incorrect output look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen. For example, what does the correct output look like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
    validations:
      required: true
  - type: input
    attributes:
      label: Code Reproduction URL
      description: Please reproduce this issue in a blank Stencil starter application and provide a link to the repo. Run `npm init stencil` to quickly spin up a Stencil project. This is the best way to ensure this issue is triaged quickly. Issues without a code reproduction may be closed if the Stencil Team cannot reproduce the issue you are reporting.
      placeholder: https://github.com/...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
